### ISSUE TITLE
the headwall 

### ISSUE THREAD

**Issue by rcullito** [rcullito/open-bounty#57]
so we march on!

**Comment by commiteth** [comment]
Balance: 0.080000 ETH
Tokens: SNT: 48.00
Contract address: [0xb85b89d151c5242bc85fce34f6bb097107188a52](https://ropsten.etherscan.io/address/0xb85b89d151c5242bc85fce34f6bb097107188a52)
Network: Testnet (Ropsten)
Status: Pending maintainer confirmation
Winner: rcullito
Visit [https://rob-open-bounty.ngrok.io](https://rob-open-bounty.ngrok.io) to learn more.
